const DATA = window.CLOUD_APP_DATA;
const STORAGE_KEY = 'cloudops-duo-progress-v2';
const LEGACY_STORAGE_KEY = 'cloudops-duo-progress-v1';
const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
let state = loadState();
let current = {phaseId:DATA.phases[0].id,lessonId:null,qIndex:0,selected:null,order:[],checked:false};

function seedState(){ return {xp:0,streak:0,completed:{},answers:{},lastDay:null,reviewQueue:{},opensCount:0,realLabDone:{},examHistory:[],labProgress:{},applicationTracker:[]}; }
function mergeState(raw){ return {...seedState(),...(raw||{}),completed:{...(raw?.completed||{})},answers:{...(raw?.answers||{})},reviewQueue:{...(raw?.reviewQueue||{})},realLabDone:{...(raw?.realLabDone||{})},labProgress:{...(raw?.labProgress||{})},examHistory:Array.isArray(raw?.examHistory)?raw.examHistory:[],applicationTracker:Array.isArray(raw?.applicationTracker)?raw.applicationTracker:[]}; }
function migrateFromV1(){ try { const v1=JSON.parse(localStorage.getItem(LEGACY_STORAGE_KEY)); return v1 ? mergeState(v1) : null; } catch { return null; } }
function loadState(){ let raw=null; try { raw=JSON.parse(localStorage.getItem(STORAGE_KEY)); } catch {} const loaded=mergeState(raw || migrateFromV1()); loaded.opensCount+=1; return loaded; }
function saveState(){ localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); }
function today(){ return new Date().toISOString().slice(0,10); }
function normalize(v){ return String(v||'').trim().toLowerCase().replace(/\s+/g,' '); }
function lessonKey(lesson){ return lesson.phaseId+':'+lesson.id; }
function getPhase(id){ return DATA.phases.find(p=>p.id===id); }
function getLesson(pid,lid){ return getPhase(pid).lessons.find(l=>l.id===lid); }
function allLessons(){ return DATA.phases.flatMap(p=>p.lessons.map(l=>({...l,phase:p,phaseId:p.id}))); }
function findQuestion(id){ return allLessons().flatMap(l=>l.questions).find(q=>q.id===id); }
function completedCount(){ return Object.values(state.completed).filter(Boolean).length; }
function dueReviewEntries(){ return Object.entries(state.reviewQueue).filter(([,q])=>state.opensCount>=q.dueAfterOpens); }
function dueCount(){ return dueReviewEntries().length; }
function updateStats(){ $('#totalXp').textContent=state.xp; $('#streak').textContent=state.streak; $('#completedLessons').textContent=completedCount(); $('#reviewDueCount').textContent=dueCount(); }
function showOnly(id){ ['dashboard','lessonScreen','labScreen','reviewScreen','examScreen','sourcesScreen'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id)); }
function safe(text){ return String(text??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function reward(q){ if(!state.answers[q.id]){ state.answers[q.id]=true; state.xp+=q.xp||10; } saveState(); updateStats(); }
function queueReview(q,ok){ if(ok){ const prev=state.reviewQueue[q.id]; if(prev){ const box=Math.min((prev.box||1)+1,3); const after={1:1,2:3,3:7}[box]; state.reviewQueue[q.id]={box,dueAfterOpens:state.opensCount+after}; } } else { state.reviewQueue[q.id]={box:1,dueAfterOpens:state.opensCount+1}; } saveState(); updateStats(); }

function renderNav(){ const nav=$('#phaseNav'); nav.innerHTML=''; DATA.phases.forEach(phase=>{ const btn=document.createElement('button'); btn.className='nav-item'; btn.dataset.phase=phase.id; btn.innerHTML=`<span class="nav-dot" style="background:${phase.color}"></span><span><b>${safe(phase.label)}</b><br><small>${safe(phase.title)}</small></span>`; btn.onclick=()=>{current.phaseId=phase.id;renderDashboard();}; nav.appendChild(btn); }); }
function renderDashboard(){ showOnly('dashboard'); $('#screenTitle').textContent='Lộ trình học tương tác v2'; $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.phase===current.phaseId)); const root=$('#dashboard'); root.innerHTML=''; DATA.phases.forEach(phase=>{ const tpl=$('#phaseCardTemplate').content.cloneNode(true); const card=$('.phase-card',tpl);card.style.borderTop=`4px solid ${phase.color}`; $('.phase-badge',tpl).textContent=`${phase.label} · ${phase.weekRange||''}`;$('.phase-badge',tpl).style.background=phase.color;const done=phase.lessons.filter(l=>state.completed[lessonKey({...l,phaseId:phase.id})]).length;$('.progress-pill',tpl).textContent=`${done}/${phase.lessons.length} lesson`; $('h3',tpl).textContent=phase.title;$('p',tpl).textContent=phase.summary; const list=$('.lesson-list',tpl);phase.lessons.forEach((lesson,i)=>{const isDone=!!state.completed[lessonKey({...lesson,phaseId:phase.id})];const btn=document.createElement('button');btn.className='lesson-btn';btn.innerHTML=`<span class="lesson-num">${isDone?'✓':i+1}</span><span><span class="lesson-title">${safe(lesson.title)}</span><span class="lesson-sub">${safe(lesson.week||'')} · ${safe(lesson.subtitle)} · ${lesson.questions.length} câu</span></span><span class="check">${isDone?'✓':'Lab + quiz'}</span>`;btn.onclick=()=>startLesson(phase.id,lesson.id);list.appendChild(btn);});root.appendChild(tpl); }); updateStats(); }
function startLesson(phaseId,lessonId){ current={phaseId,lessonId,qIndex:0,selected:null,order:[],checked:false}; renderLesson(); }
function renderLesson(){ showOnly('lessonScreen'); const phase=getPhase(current.phaseId),lesson=getLesson(current.phaseId,current.lessonId),q=lesson.questions[current.qIndex]; $('#screenTitle').textContent=`${phase.label}: ${phase.title}`;const pct=Math.round((current.qIndex/lesson.questions.length)*100);$('#lessonScreen').innerHTML=`<div class="lesson-header"><div><button class="ghost-btn" id="backBtn">← Về lộ trình</button><h3>${safe(lesson.title)}</h3><p class="lesson-meta">${safe(lesson.week||'')} · ${safe(lesson.subtitle)}</p></div><div><a class="ghost-btn" href="${DATA.sources.find(s=>lesson.sourceIds.includes(s.id))?.url||'#'}" target="_blank" rel="noopener">Xem video nguồn</a><button class="primary-btn lab-open" id="openLabBtn">Lab mô phỏng</button></div></div><div class="why-box"><b>Vì sao quan trọng:</b> ${safe(lesson.whyImportant||'')}</div><div class="lab-box"><b>Lab trên máy thật:</b> ${safe(lesson.lab)}</div><div class="progressbar"><div style="width:${pct}%"></div></div><div class="question-card" id="questionCard"></div>`; $('#backBtn').onclick=renderDashboard;$('#openLabBtn').onclick=()=>renderLab(phase,lesson);renderQuestion(q); }
function typeLabel(type){ return ({mcq:'Trắc nghiệm',fill:'Điền từ',order:'Xếp từ',terminal:'Terminal',scenario:'Tình huống',match:'Ghép cặp',diagram:'Sơ đồ',calc:'Tính toán',codefix:'Sửa code'})[type]||type; }
function renderQuestion(q){ current.selected=null;current.order=[];current.checked=false;const card=$('#questionCard');card.innerHTML=`<div class="question-type">${typeLabel(q.type)} · Câu ${current.qIndex+1}/${getLesson(current.phaseId,current.lessonId).questions.length} · ${q.xp} XP</div><div class="prompt">${safe(q.prompt)}</div><div id="answerArea"></div><div id="feedback"></div><div class="question-actions"><button class="ghost-btn" id="hintBtn">Gợi ý</button><button class="ghost-btn" id="resetBtn">Làm lại</button><button class="primary-btn" id="checkBtn">Kiểm tra</button></div>`; const area=$('#answerArea');
  if(q.type==='mcq'){ area.className='options';q.options.forEach(opt=>{const b=document.createElement('button');b.className='option';b.textContent=opt;b.onclick=()=>{$$('.option',area).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');current.selected=opt;};area.appendChild(b);}); }
  else if(q.type==='fill'||q.type==='calc'||q.type==='terminal'){ const terminal=q.type==='terminal';area.innerHTML=`<div class="${terminal?'terminal-ui':''}">${terminal?`<pre>${safe(q.startingOutput||'learner@cloudops:~$ ')}</pre>`:''}<input id="freeAnswer" class="fill-input ${terminal?'terminal-input':''}" ${q.type==='calc'?'type="number" step="any"':''} placeholder="${terminal?'Gõ lệnh và nhấn Enter...':'Nhập đáp án...'}" autocomplete="off" /></div>`; const input=$('#freeAnswer');input.oninput=e=>current.selected=e.target.value;input.onkeydown=e=>{if(e.key==='Enter')checkAnswer(q);};input.focus(); }
  else if(q.type==='order'){area.innerHTML='<div class="answer-bank" id="answerBank"></div><div class="word-bank" id="wordBank"></div>';q.words.forEach((w,i)=>{const b=document.createElement('button');b.className='word-chip';b.textContent=w;b.onclick=()=>{if(b.classList.contains('used'))return;b.classList.add('used');current.order.push({w,i});renderOrderAnswer(q);};$('#wordBank').appendChild(b);});}
  else if(q.type==='match'||q.type==='diagram'){renderPairQuestion(q,area);}
  else if(q.type==='scenario'){renderScenario(q,area);}
  else if(q.type==='codefix'){area.innerHTML=`<pre class="code-block">${q.lines.map((line,i)=>`<button class="code-line" data-line="${i+1}">${safe(line)}</button>`).join('')}</pre><input id="codeFixInput" class="fill-input" placeholder="Gõ bản sửa ngắn..."/>`;$$('.code-line',area).forEach(b=>b.onclick=()=>{const prev=$('.code-line.selected',area);if(prev)prev.classList.remove('selected');b.classList.add('selected');current.selected={line:Number(b.dataset.line),fix:$('#codeFixInput').value};});$('#codeFixInput').oninput=e=>{const picked=$('.code-line.selected',area);current.selected={line:picked?Number(picked.dataset.line):null,fix:e.target.value};};}
  $('#hintBtn').onclick=()=>showHint(q);$('#resetBtn').onclick=()=>renderQuestion(q);$('#checkBtn').onclick=()=>checkAnswer(q);
}
function showHint(q){ const f=$('#feedback');f.className='feedback';f.innerHTML=`💡 Gợi ý: ${safe(q.hint||'Đọc từng điều kiện; ưu tiên quan sát trước khi thay đổi.')}`; }
function renderOrderAnswer(q){const bank=$('#answerBank');bank.innerHTML='';current.order.forEach((item,index)=>{const b=document.createElement('button');b.className='word-chip';b.textContent=item.w;b.onclick=()=>{current.order.splice(index,1);const chip=$$('#wordBank .word-chip').find(x=>x.textContent===item.w&&!x.classList.contains('used'));if(chip)chip.classList.remove('used');renderOrderAnswer(q);};bank.appendChild(b);});}
function renderPairQuestion(q,area){let left=null,right=null;const pairMap=new Map(q.pairs);const shuffled=[...q.pairs.map(x=>x[1])].sort(()=>Math.random()-.5);area.innerHTML=`<div class="match-grid"><div>${q.pairs.map((p,i)=>`<button class="match-item left" data-key="${i}">${safe(p[0])}</button>`).join('')}</div><div>${shuffled.map((v,i)=>`<button class="match-item right" data-value="${i}">${safe(v)}</button>`).join('')}</div></div><p id="matchStatus" class="lesson-meta">Chọn một mục bên trái, rồi một mục bên phải.</p>`; const chosen=[];const commit=()=>{if(left===null||right===null)return;chosen.push([q.pairs[left][0],shuffled[right]]);$(`.left[data-key="${left}"]`,area).classList.add('paired');$(`.right[data-value="${right}"]`,area).classList.add('paired');left=null;right=null;current.selected=chosen;$('#matchStatus').textContent=`Đã ghép ${chosen.length}/${q.pairs.length} cặp.`;};$$('.left',area).forEach(b=>b.onclick=()=>{if(b.classList.contains('paired'))return;left=Number(b.dataset.key);$$('.left',area).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');commit();});$$('.right',area).forEach(b=>b.onclick=()=>{if(b.classList.contains('paired'))return;right=Number(b.dataset.value);$$('.right',area).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');commit();});}
function renderScenario(q,area){let idx=0,score=0;const paint=()=>{const step=q.steps[idx];area.innerHTML=`<div class="scenario-score">Điểm quyết định: ${score}</div><h4>${safe(step.prompt)}</h4><div class="options">${step.options.map((o,i)=>`<button class="option" data-i="${i}">${safe(o.label)}</button>`).join('')}</div>`;$$('.option',area).forEach(b=>b.onclick=()=>{const o=step.options[Number(b.dataset.i)];score+=o.points;idx++;if(idx<q.steps.length)paint();else{area.innerHTML=`<div class="feedback ${score>=q.passScore?'good':'bad'}">Kết thúc tình huống: ${score} điểm.</div>`;current.selected=score;}});};paint();}
function answerOk(q){if(q.type==='order')return normalize(current.order.map(x=>x.w).join(' '))===normalize(q.answer);if(q.type==='terminal')return [q.answer,...(q.acceptableAnswers||[])].some(a=>normalize(a)===normalize(current.selected));if(q.type==='calc')return Math.abs(Number(current.selected)-Number(q.answer))<=Number(q.tolerance||0);if(q.type==='match'||q.type==='diagram')return Array.isArray(current.selected)&&current.selected.length===q.pairs.length&&current.selected.every(([a,b])=>q.pairs.some(p=>p[0]===a&&p[1]===b));if(q.type==='scenario')return Number(current.selected)>=q.passScore;if(q.type==='codefix')return current.selected?.line===q.badLine&&(q.acceptableAnswers||[q.answer]).some(a=>normalize(current.selected.fix)===normalize(a));return normalize(current.selected)===normalize(q.answer);}
function checkAnswer(q){if(current.checked){nextQuestion();return;}const ok=answerOk(q);const fb=$('#feedback');fb.className='feedback '+(ok?'good':'bad');const answer=q.type==='match'||q.type==='diagram'||q.type==='scenario'?'Xem kết quả bên trên':q.answer;fb.innerHTML=`${ok?'✅ Đúng!':'❌ Chưa đúng.'}<div class="question-explain">Đáp án: <span class="kbd">${safe(answer)}</span><br>${safe(q.explanation||'')}</div>`;if(q.type==='terminal'&&current.selected)fb.innerHTML+=`<pre class="terminal-output">${safe(q.simulatedOutput||'-- command accepted --')}</pre>`;if(ok)reward(q);queueReview(q,ok);current.checked=true;$('#checkBtn').textContent=current.qIndex===getLesson(current.phaseId,current.lessonId).questions.length-1?'Hoàn tất lesson':'Câu tiếp theo';}
function nextQuestion(){const lesson=getLesson(current.phaseId,current.lessonId);if(current.qIndex<lesson.questions.length-1){current.qIndex++;renderLesson();return;}completeLesson(lesson);}
function completeLesson(lesson){const key=lessonKey({...lesson,phaseId:current.phaseId});state.completed[key]=true;const day=today();if(state.lastDay!==day){state.streak+=1;state.lastDay=day;}saveState();updateStats();$('#lessonScreen').innerHTML=`<div class="complete-panel"><div class="big">🏆</div><h3>Hoàn tất ${safe(lesson.title)}</h3><p>Bạn đã hoàn thành quiz sâu. Bước kế tiếp: mở Lab mô phỏng, sau đó làm lại trên máy/cloud thật và lưu runbook/commit.</p><br><button class="primary-btn" id="completeLabBtn">Mở Lab mô phỏng</button><button class="ghost-btn" id="continueBtn">Tiếp tục lộ trình</button></div>`;$('#completeLabBtn').onclick=()=>renderLab(getPhase(current.phaseId),lesson);$('#continueBtn').onclick=renderDashboard;}

function renderLab(phase,lesson){showOnly('labScreen');$('#screenTitle').textContent=`Lab: ${lesson.title}`;const lab=lesson.labSim;const root=$('#labScreen');root.innerHTML=`<div class="lesson-header"><div><button class="ghost-btn" id="backLessonBtn">← Quay lại lesson</button><h3>${safe(lab.title||'Lab mô phỏng')}</h3><p class="lesson-meta">Mô phỏng để luyện tư duy; vẫn cần thực hành thật để tạo bằng chứng portfolio.</p></div></div><div id="labWorkspace"></div><div class="lab-footer"><button class="ghost-btn" id="labHintBtn">Gợi ý</button><button class="ghost-btn" id="labAnswerBtn">Xem đáp án mẫu</button><label class="real-lab"><input id="realLabCheck" type="checkbox" ${state.realLabDone[lesson.id]?'checked':''}/> Tôi đã tự làm lại thao tác này trên máy/cloud thật (+20 XP)</label><button class="primary-btn" id="finishLabBtn">Lưu Lab</button></div><div id="labFeedback"></div>`;$('#backLessonBtn').onclick=renderLesson;renderLabKind(lab,lesson);$('#labHintBtn').onclick=()=>labFeedback('💡 Gợi ý: dùng dữ kiện hiển thị trong simulator, đi từ kiểm tra an toàn đến thay đổi có kiểm soát.');$('#labAnswerBtn').onclick=()=>labFeedback(`Đáp án mẫu: ${safe(sampleLabAnswer(lab))}`);$('#finishLabBtn').onclick=()=>{if($('#realLabCheck').checked&&!state.realLabDone[lesson.id]){state.realLabDone[lesson.id]=true;state.xp+=20;}state.labProgress[lesson.id]={done:true,at:new Date().toISOString()};saveState();updateStats();labFeedback('✅ Đã lưu tiến độ Lab. Hãy lưu screenshot/runbook thật vào portfolio.','good');};}
function labFeedback(text,kind=''){const f=$('#labFeedback');f.className='feedback '+kind;f.textContent=text;}
function sampleLabAnswer(lab){if(lab.kind==='terminal')return lab.tasks.map(t=>t.expect).join(' → ');if(lab.kind==='awsDiagram')return 'IGW → Internet edge; public subnet/NAT → Public layer; private subnet → Private layer; Security Group → Security boundary.';if(lab.kind==='terraformCli')return 'Có resource hợp lệ, chạy plan để thấy số add/change/destroy, chỉ apply sau review.';if(lab.kind==='kubectlCli')return `${lab.expectCommand}, đọc events/logs rồi sửa nguyên nhân thay vì chỉ restart.`;if(lab.kind==='promqlConsole')return lab.expectedQuery;if(lab.kind==='examMode')return 'Làm đủ 65 câu, xem review và biến câu yếu thành ôn Leitner.';return 'Đọc yêu cầu và kiểm tra từng điều kiện.';}
function renderLabKind(lab,lesson){const w=$('#labWorkspace');if(lab.kind==='terminal')renderTerminalLab(lab,w,lesson);else if(lab.kind==='awsDiagram')renderAwsLab(lab,w);else if(lab.kind==='terraformCli')renderTerraformLab(lab,w);else if(lab.kind==='kubectlCli')renderKubectlLab(lab,w);else if(lab.kind==='promqlConsole')renderPromLab(lab,w);else if(lab.kind==='examMode')renderExamEntry(lab,w);}
function renderTerminalLab(lab,w,lesson){let task=0;w.innerHTML=`<div class="task-list">${lab.tasks.map((t,i)=>`<p id="task-${i}">${i===0?'▶':'○'} ${safe(t.instruction)}</p>`).join('')}</div><div class="terminal-ui"><pre id="terminalLog">CloudOps Linux simulator\nlearner@cloudops:~$ </pre><input id="terminalCmd" class="fill-input terminal-input" placeholder="gõ lệnh..."/></div>`;const input=$('#terminalCmd');input.focus();input.onkeydown=e=>{if(e.key!=='Enter')return;const cmd=input.value.trim();const out=$('#terminalLog');out.textContent+=cmd+'\n';const expected=lab.tasks[task]?.expect||'';if(normalize(cmd)===normalize(expected)){out.textContent+='✓ command accepted\n';$(`#task-${task}`).textContent='✓ '+lab.tasks[task].instruction;task++;if(task<lab.tasks.length){$(`#task-${task}`).textContent='▶ '+lab.tasks[task].instruction;out.textContent+='learner@cloudops:~$ ';}else out.textContent+='✅ All simulated tasks completed.';}else out.textContent+='Không đúng task hiện tại. Thử ls, systemctl, journalctl, grep, ss, docker hoặc git theo ngữ cảnh.\nlearner@cloudops:~$ ';input.value='';};}
function renderAwsLab(lab,w){const used={};w.innerHTML=`<p>${safe(lab.rules.join(' '))}</p><div class="diagram-lab"><div class="diagram-nodes">${lab.nodes.map(n=>`<button class="drag-node" data-node="${safe(n)}">${safe(n)}</button>`).join('')}</div><div class="diagram-slots">${lab.slots.map(s=>`<div class="diagram-slot" data-slot="${safe(s)}"><b>${safe(s)}</b><span>kéo/click node vào đây</span></div>`).join('')}</div></div><button class="primary-btn" id="validateDiagram">Validate architecture</button>`;let selected=null;$$('.drag-node',w).forEach(b=>b.onclick=()=>{selected=b.dataset.node;$$('.drag-node',w).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');});$$('.diagram-slot',w).forEach(slot=>slot.onclick=()=>{if(!selected)return;slot.dataset.node=selected;slot.querySelector('span').textContent=selected;used[selected]=slot.dataset.slot;});$('#validateDiagram').onclick=()=>{const correct=Object.entries(lab.expected).filter(([n,s])=>used[n]===s).length;labFeedback(correct>=3?`✅ ${correct}/${Object.keys(lab.expected).length} rule/placement đúng. Kiến trúc đủ điều kiện tối thiểu.`:`❌ Mới đúng ${correct}. Kiểm tra lại IGW/public route, NAT/private subnet và Security Group.` ,correct>=3?'good':'bad');};}
function renderTerraformLab(lab,w){w.innerHTML=`<textarea id="tfCode" class="code-editor">${safe(lab.starter)}</textarea><div class="question-actions"><button class="ghost-btn" id="tfPlan">terraform plan</button><button class="primary-btn" id="tfApply" disabled>terraform apply</button></div><pre id="tfOut" class="terminal-output"></pre>`;$('#tfPlan').onclick=()=>{const code=$('#tfCode').value;const found=(code.match(/resource\s+"/g)||[]).length;const ok=found>=1;$('#tfOut').textContent=ok?`Plan: ${lab.expectedPlan.add} to add, ${lab.expectedPlan.change} to change, ${lab.expectedPlan.destroy} to destroy.\n+ simulated_resource.example`:'Error: cần ít nhất một resource block hợp lệ.';$('#tfApply').disabled=!ok;};$('#tfApply').onclick=()=>{labFeedback('✅ Apply mô phỏng hoàn tất. Trong lab thật hãy chạy plan, review, apply và terraform destroy sau khi có bằng chứng.','good');};}
function renderKubectlLab(lab,w){const logs={CrashLoopBackOff:'Error: missing DATABASE_URL\ncontainer exits with code 1',Pending:'0/2 nodes available: insufficient cpu; node has taint',ImagePullBackOff:'Failed to pull image registry.invalid/api:v2: not found'};w.innerHTML=`<div class="terminal-ui"><pre id="kubeOut">cluster: lab-cluster\npod/api-7d9f status: ${lab.fault}\n</pre><input id="kubeCmd" class="fill-input terminal-input" placeholder="gõ kubectl get/describe/logs..."/></div><div class="options" id="fixOptions">${lab.fixOptions.map((x,i)=>`<button class="option" data-i="${i}">${safe(x)}</button>`).join('')}</div>`;$('#kubeCmd').onkeydown=e=>{if(e.key==='Enter'){const cmd=e.target.value;const out=$('#kubeOut');out.textContent+=`learner$ ${cmd}\n${normalize(cmd).includes('logs')?logs[lab.fault]:normalize(cmd).includes('describe')?`Events: ${logs[lab.fault]}`:'NAME READY STATUS\napi-7d9f 0/1 '+lab.fault}\n`;e.target.value='';}};$$('#fixOptions .option').forEach(b=>b.onclick=()=>{const ok=Number(b.dataset.i)===lab.correctFix;labFeedback(ok?'✅ Fix hợp lý: sửa nguyên nhân rồi rollout/apply có kiểm soát.':'❌ Đây là hành động che dấu hoặc phá dữ kiện. Đọc describe/logs trước.',ok?'good':'bad');});}
function renderPromLab(lab,w){w.innerHTML=`<p>Mock metric: <span class="kbd">up{job="api"}=1</span>, <span class="kbd">up{job="worker"}=0</span>, <span class="kbd">http_requests_total</span>.</p><div class="terminal-ui"><input id="promQuery" class="fill-input terminal-input" placeholder="gõ PromQL..."/><button class="primary-btn" id="runProm">Run query</button></div><div id="spark"></div>`;$('#runProm').onclick=()=>{const q=$('#promQuery').value;const ok=normalize(q)===normalize(lab.expectedQuery);$('#spark').innerHTML=`<pre class="terminal-output">${ok?'result: [api=1, worker=0]':'query parsed on mock data; thử đúng biểu thức task.'}</pre><svg class="sparkline" viewBox="0 0 240 60"><polyline points="0,45 30,38 65,42 95,18 130,28 170,10 205,25 240,12" fill="none" stroke="#38bdf8" stroke-width="4"/></svg>`;labFeedback(ok?'✅ Query khớp task. Hãy giải thích metric này dẫn tới action nào.':'❌ Chưa khớp query mục tiêu.',ok?'good':'bad');};}
function renderExamEntry(lab,w){w.innerHTML=`<div class="exam-intro"><h3>Thi thử SAA-C03</h3><p>65 câu mô phỏng, ${lab.durationMinutes} phút. Đáp án chỉ hiện sau khi nộp. Điểm mục tiêu: ≥82%.</p><button class="primary-btn" id="startExamBtn">Bắt đầu thi thử</button></div>${lab.tracker?applicationTrackerHTML():''}`;$('#startExamBtn').onclick=()=>startExam(lab.questionCount,lab.durationMinutes);if(lab.tracker)bindTracker();}
function applicationTrackerHTML(){return `<div class="tracker"><h3>Application tracker — Week 25</h3><div id="trackerRows">${state.applicationTracker.map((r,i)=>`<p>${safe(r.company)} · ${safe(r.keywords)} · ${safe(r.cv)} · ${safe(r.followup)}</p>`).join('')||'<p>Chưa có application nào.</p>'}</div><input id="companyInput" class="fill-input" placeholder="Công ty / job title"/><input id="keywordInput" class="fill-input" placeholder="JD keywords hoặc skill gap"/><input id="cvInput" class="fill-input" placeholder="CV version / ngày follow-up"/><button class="ghost-btn" id="addApplication">Thêm application</button></div>`;}
function bindTracker(){const b=$('#addApplication');if(!b)return;b.onclick=()=>{const company=$('#companyInput').value.trim(),keywords=$('#keywordInput').value.trim(),cv=$('#cvInput').value.trim();if(!company)return;state.applicationTracker.push({company,keywords,cv,followup:new Date().toISOString().slice(0,10)});saveState();renderLab(getPhase(current.phaseId),getLesson(current.phaseId,current.lessonId));};}

let exam=null;
function startExam(count,minutes){const pool=[...DATA.saaExamPool].sort(()=>Math.random()-.5).slice(0,count);exam={pool,index:0,answers:{},endsAt:Date.now()+minutes*60*1000,timer:null};renderExam();exam.timer=setInterval(()=>{if(!exam)return;const sec=Math.max(0,Math.ceil((exam.endsAt-Date.now())/1000));const t=$('#examTimer');if(t)t.textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;if(sec<=0)submitExam();},500);}
function renderExam(){showOnly('examScreen');$('#screenTitle').textContent='Thi thử SAA-C03';const q=exam.pool[exam.index];$('#examScreen').innerHTML=`<div class="lesson-header"><div><h3>Câu ${exam.index+1}/${exam.pool.length}</h3><p id="examTimer" class="exam-timer">--:--</p></div><button class="danger-btn" id="submitExamBtn">Nộp bài</button></div><div class="question-card"><div class="prompt">${safe(q.prompt)}</div><div class="options">${q.options.map((o,i)=>`<button class="option ${exam.answers[q.id]===o?'selected':''}" data-i="${i}">${safe(o)}</button>`).join('')}</div></div><div class="question-actions"><button class="ghost-btn" id="prevExam" ${exam.index===0?'disabled':''}>← Câu trước</button><button class="primary-btn" id="nextExam">${exam.index===exam.pool.length-1?'Xem lại / nộp':'Câu tiếp →'}</button></div>`;$$('#examScreen .option').forEach(b=>b.onclick=()=>{exam.answers[q.id]=q.options[Number(b.dataset.i)];renderExam();});$('#prevExam').onclick=()=>{exam.index--;renderExam();};$('#nextExam').onclick=()=>{if(exam.index<exam.pool.length-1){exam.index++;renderExam();}else submitExam();};$('#submitExamBtn').onclick=submitExam;}
function submitExam(){if(!exam)return;clearInterval(exam.timer);const score=exam.pool.filter(q=>exam.answers[q.id]===q.answer).length;const pct=Math.round(score/exam.pool.length*100);state.examHistory.push({date:new Date().toISOString(),score,total:exam.pool.length});saveState();exam=null;showOnly('examScreen');$('#examScreen').innerHTML=`<div class="complete-panel"><div class="big">${pct>=82?'🏆':'📚'}</div><h3>Kết quả: ${score}/65 (${pct}%)</h3><p>${pct>=82?'Đạt mục tiêu mock exam ≥82%. Hãy rà lại giải thích và giữ nhịp lab thật.':'Chưa đạt mốc 82%. Chọn các chủ đề sai để biến thành flashcard/ôn Leitner trước lần thi tiếp.'}</p><p class="lesson-meta">Lịch sử gần nhất: ${state.examHistory.slice(-3).map(x=>`${x.score}/${x.total}`).join(' · ')}</p><button class="primary-btn" id="examHome">Về lộ trình</button></div>`;$('#examHome').onclick=renderDashboard;}

function renderReview(){showOnly('reviewScreen');$('#screenTitle').textContent='Ôn tập Leitner';const due=dueReviewEntries();const root=$('#reviewScreen');if(!due.length){root.innerHTML=`<div class="complete-panel"><div class="big">✅</div><h3>Không có câu đến hạn</h3><p>Những câu sai sẽ xuất hiện lại sau 1 lần mở app, sau đó 3 và 7 lần tùy Leitner box.</p><button class="primary-btn" id="reviewHome">Về lộ trình</button></div>`;$('#reviewHome').onclick=renderDashboard;return;}let pos=0;const paint=()=>{const [id,entry]=due[pos],q=findQuestion(id);if(!q){delete state.reviewQueue[id];saveState();renderReview();return;}root.innerHTML=`<div class="lesson-header"><div><button class="ghost-btn" id="reviewBack">← Về lộ trình</button><h3>Ôn câu ${pos+1}/${due.length} · Box ${entry.box}</h3></div></div><div class="question-card"><div class="prompt">${safe(q.prompt)}</div><p class="lesson-meta">Tự trả lời trước, rồi bấm lật để xem giải thích.</p><button class="ghost-btn" id="flipCard">Lật đáp án</button><div id="reviewAnswer" class="hidden feedback good">${safe(q.answer||'Xem kết quả mô phỏng')}<br>${safe(q.explanation||'')}</div><div class="question-actions"><button class="danger-btn" id="reviewAgain">Chưa nhớ</button><button class="primary-btn" id="reviewGot">Đã nhớ</button></div></div>`;$('#reviewBack').onclick=renderDashboard;$('#flipCard').onclick=()=>$('#reviewAnswer').classList.remove('hidden');const advance=ok=>{queueReview(q,ok);pos++;if(pos>=due.length)renderReview();else paint();};$('#reviewAgain').onclick=()=>advance(false);$('#reviewGot').onclick=()=>advance(true);};paint();}
function renderSources(){showOnly('sourcesScreen');$('#screenTitle').textContent='Nguồn YouTube và tài liệu';$('#sourcesScreen').innerHTML=`<h3>Nguồn đã kiểm tra</h3><p class="lesson-meta">App chỉ lưu URL, tiêu đề và câu hỏi tự biên soạn; không sao chép transcript.</p><div class="source-grid">${DATA.sources.map(s=>`<div class="source-item"><b>${safe(s.channel)}</b><p>${safe(s.title)}</p><p>Transcript: ${safe(s.transcript)}</p><a href="${s.url}" target="_blank" rel="noopener">Mở YouTube</a></div>`).join('')}</div><br><button class="ghost-btn" id="backSources">← Về lộ trình</button>`;$('#backSources').onclick=renderDashboard;}
$('#openSourcesBtn').onclick=renderSources;$('#openReviewBtn').onclick=renderReview;$('#openExamBtn').onclick=()=>startExam(65,90);renderNav();saveState();renderDashboard();
